### ISSUE TITLE
能否找出订阅的api

### ISSUE THREAD

**Issue by Sausure** [izzyleung/ZhihuDailyPurify#10]
你好，我发现知乎日报可以滑出侧栏选择感兴趣的订阅然后再首页推送，请问这个是怎么实现的？

**Comment by izzyleung** [comment]
请参阅 https://github.com/izzyleung/ZhihuDailyPurify/issues/1#issuecomment-46288615

抱歉，我已经很久没有使用知乎日报，并且我对订阅的功能并不感兴趣。

所以如果可能的话，请麻烦您通过我提到的方式，测试出您需要的 API 吧！

**Comment by Sausure** [comment]
你好，我该怎么测试出我需要的api呢

**Comment by Sausure** [comment]
多谢，我知道了！！
