### ISSUE TITLE
请问如何判断最新消息已经下载过？（详）

### ISSUE THREAD

**Issue by CodingNinjaOctocat** [izzyleung/ZhihuDailyPurify#11]
其实我真正的意思是：我现在获取了最新消息的列表，过了几个小时，假设最新消息尚未有更新，这时由于刷新操作、或再次打开应用，应用就会去获取最新消息不是耗流量吗？但话说回来，我不获取的话也就不知道它有没有更新。难道真的没有任何方法解决这种问题吗？

**Comment by izzyleung** [comment]
倒是有一个办法：在自己的服务器上面编写一个应用，每隔一分钟便去查阅知乎日报的数据，检查是否有新的数据。

在自己的软件中，使用自己的服务器进行查询，查询的时候增加一个参数：上一次软件更新的时间。服务器端的程序便只需要返回上次更新后新增加的数据。

这个做法听起来貌似很美好，但是却仍然存在着很多的问题：
1. 频繁地查询会增加知乎日报服务器的负载，一旦当他们察觉，你所使用的服务器 IP 就会被封杀（SAE 和 GAE 的 IP 就是因为有人抓数据的频率太频繁而被封锁的）
2. 服务器端的程序需要去处理各种各样的情况：如果曾经的一条信息被删除，如何返回数据？如果那条信息只是标题变了，又应该怎么去做？如果信息的顺序发生变化，又应该怎么返回数据告诉客户端以保持数据和知乎日报的数据一致？

但是不知道您是否有查询过一次更新所使用的流量呢？我记得知乎日报每次更新所需要的数据量仅仅只是 1kb 的样子。

所以如果仅仅只是为了节省小于 1kb 的流量而去花费如此大的精力，实属不值得啊～
