### ISSUE TITLE
top stories的title突然变成了乱码

### ISSUE THREAD

**Issue by Zane-cqupt** [izzyleung/ZhihuDailyPurify#13]
之前app写的时候用的都好好的，突然变成了乱码

**Comment by izzyleung** [comment]
很抱歉，您的描述实在是太简略了，我很难从三言两语中推断出引起乱码的原因。
而且我不知道为什么，在我所在地区的网络环境中，并没有出现 Top Stories 的 title 乱码的问题。

不知道您可否提供更相信的信息呢，比如，和乱码相关部分的代码，网络环境，或者是使用的 Android 版本，手机型号和编译所使用的环境信息？

不过我推测有几个可能引起乱码的地方，如果您可以使用以下的检查点做逐一排查，或许能够找到引起乱码的原因：

* 使用 UTF-8 作为解析服务器返回数据的默认编码
* 使用知乎日报的官方 App 检查是否是因为服务器的数据出现了问题而导致的乱码
* 使用浏览器访问 API 所在的网址，检查是否是因为官方对于数据做了特殊的处理而导致乱码
* 强制使用 HTTP Header 中所指名的 Content-Type 中的 charset（如果它不是 UTF-8）

附：知乎日报服务器 HTTP Response Header
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 2065
Content-Type: application/json; charset=UTF-8
Date: Thu, 29 Oct 2015 19:34:28 GMT
ETag: "8a5d394f6b1344732e863e3d984ba176be5a3483"
Server: zhihu_nginx
Vary: Accept-Encoding
X-Backend: daily01
```
