### ISSUE TITLE
请问下ajax请求获取主题日报列表跨域访问出错，这种情况下怎么获取数据呢。

### ISSUE THREAD

**Issue by minhuang0** [izzyleung/ZhihuDailyPurify#14]
chrome  47.0.2526.111 (64-bit) , osx 10.11
```
XMLHttpRequest cannot load http://news-at.zhihu.com/api/4/themes?_=1456985006563. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
```
有没有方式以web的方式获取到数据呢。

**Comment by kaizhang0124** [comment]
您好，这个项目只是我在学习swif过程中练习的一个项目，具体信息不是很了解，对不起

在 2016-03-03 14:11:13，"Min Huang" <notifications@github.com> 写道：


chrome 47.0.2526.111 (64-bit) , osx 10.11

XMLHttpRequest cannot load http://news-at.zhihu.com/api/4/themes?_=1456985006563. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.


有没有方式以web的方式获取到数据呢。

**Comment by minhuang0** [comment]
@kaizhang0124 没事的，谢谢了。
