### ISSUE TITLE
对于多question的文章，弹出的选择dialog内容点击后应该是进入观看而不是分享吧

### ISSUE THREAD

**Issue by nadazero** [izzyleung/ZhihuDailyPurify#18]
对于多question的文章，弹出的选择dialog内容点击后应该是进入观看而不是分享吧。
逻辑上说不通吧。还是改成以下这样？

private DialogInterface.OnClickListener makeGoToZhihuDialogClickListener(Context context, DailyNews dailyNews) {
......
            shareQuestion(context, questionTitle, questionUrl); // -> 改为 goToZhihu(context, questionUrl);
......
    }

**Comment by izzyleung** [comment]
Thanks for your response, the issue has been fixed.
