### ISSUE TITLE
批量获取图片的时候403 forbidden

### ISSUE THREAD

**Issue by ifmos** [izzyleung/ZhihuDailyPurify#19]
你好，我用是latest这个API，里面返回的数据里有images的url地址，我用angular的ng-repeat生成的时候返回403，而直接吧url地址粘贴到地址栏可以打开，能不能问一下该如何解决呀~

**Comment by izzyleung** [comment]
这应该是因为知乎的服务器禁止了图片的外链。

您可以尝试着将图片保存至服务器之后，展示本地的文件而不是保存在知乎的服务器上的图片。
