### ISSUE TITLE
启动界面图像获取不正确

### ISSUE THREAD

**Issue by mcxinyu** [izzyleung/ZhihuDailyPurify#20]
获取的图片与知乎日报的启动页不一致，而且好像图片好久没更新了。能否教授怎么使用非正常手段？

**Comment by littlepiggy03** [comment]
不从缓存读取即可，如果不行，可以在请求的网址后面加一个时间戳，如：
`http://news-at.zhihu.com/api/4/start-image/1080*1776?t=201609241859`
