### ISSUE TITLE
消息内容获取与离线下载 消息内容获取不完整

### ISSUE THREAD

**Issue by jesse920524** [izzyleung/ZhihuDailyPurify#21]
### **WebActivity: response is {"body":"<div class=\"main-wrap content-wrap\">\n<div class=\"headline\">\n\n<div class=\"img-place-holder\"><\/div>\n\n\n\n<\/div>\n\n<div class=\"content-inner\">\n\n\n\n\n<div class=\"question\">\n<h2 class=\"question-title\">如何评价谷歌的「人工智能先行」（AI First）战略？<\/h2>\n\n<div class=\"answer\">\n\n<div class=\"meta\">\n<img class=\"avatar\" src=\"http:\/\/pic2.zhimg.com\/14c3b9763ead3bbb4f0e6fd6a4e32c59_is.jpg\">\n<span class=\"author\">严肃，<\/span><span class=\"bio\">这是一个不平衡的世界<\/span>\n<\/div>\n\n<div class=\"content\">\n<p>先看看为什么要从 Mobile First（移动第一）转向 AI First （人工智能第一）<\/p>\r\n<p><strong>首先，是时候调整 Mobile First 的战略了。<\/strong><\/p>\r\n<p>根据 KPCB 女王的报告,移动互联网用户增速已经首次放缓<\/p>\r\n<blockquote>- 全球智能手机用户数比上年增长 21%，去年增长 31%，增速放缓；在经过 5 年高增长后，2015 年全球智能手机出货量增长 10%，去年增长 28%<\/blockquote>\r\n<p>移动互联网从硬件到工具再到内容，整个移动互联网产业链都非常成熟了，大的创新的机会已经很少了。<\/p>\r\n<p>而个人跟踪硅谷公司的新产品的体会也是，移动互联网让人眼前一亮的产品基本很少了，而移动设备的硬件发展至今也是大同小异了，没有大的突破。<\/p>\r\n<p><strong>接下来看看 AI 现在和未来的市场有多大。<\/strong><\/p>\r\n<p><strong>先看看 AI 当前有哪些应用场景：<\/strong><\/p>\r\n<p>人工智能技术服务人类已经很久了，好的人工智能技术使用的时候往往让我们察觉不到它的存在。<\/p>\r\n<p>比如搜索就是 Information Retrieval 的应用，推荐系统也是人工智能的应用。<\/p>\r\n<p>必须要承认，现在 AI 的发展还是非常早期阶段，很多技术其实并不成熟，但是 AI 某些细分领域的商业化已经可以做起来了。<\/p>\r\n<p>目前在人工智能领域，相对成熟的领域（可以应用于工业界），主要有知识图谱、自然语言处理、翻译、语音识别、图像识别等。<\/p>\r\n<p><img class=\"content-image\" src=\"http:\/\/pic3.zhimg.com\/70\/715ae19f7e4e43e186d8c2d2b54a87da_b.jpg\" alt=\"\" \/><\/p>\r\n<p>其中任何单一个方面的应用都可以有非常大的想象空间：<\/p>\r\n<p>比如语音识别，这是一块技术很成熟，但是应用的前景依旧是一片蓝海。<\/p>\r\n<p>语音作为认为一种非常自然的交互方式，在可穿戴设备、医疗领域、智能家居、教育领域等方面有大量的应用场景，比如出门问问的 ticwear。<\/p>\r\n<p>&nbsp;<\/p>\r\n<p>再说说知识图谱，把知识图谱应用细分领域，比如地产、电子商务、金融，实际上国内外都已经有公司在做这个事情了，每一块都是很大的市场。比如美国的 AlphaSense，国内的文因互联。<\/p>\r\n<p>图像识别也是一个潜在应用广泛的领域，目前的广泛应用的有光学字符识别（Optical Character Recognition）、人脸识别等,这也是一个万亿级别的市场。<\/p>\r\n<p>把多种人工智能技术结合在一起的想象空间更大，典型的例子 Google Assistant。<\/p>\r\n<p><strong>那么未来 AI First 有哪些应用场景？<br \/><\/strong><\/p>\r\n<p>未来随着 AI 技术的成熟、数据的积累以及智能设备的普及，AI 在很多领域会有大的爆发。<\/p>\r\n<p>简单的例子，如果自然语音处理技术继续成熟，conversation UI(会话式 UI)极有可能取代 APP 成为下一代服务的入口，这是一个可能可以颠覆搜索引擎和 APP 的应用场景。<\/p>\r\n<p><img class=\"content-image\" src=\"http:\/\/pic2.zhimg.com\/70\/64a5f85340b99dd7221298fca7599bf1_b.jpg\" alt=\"\" \/><\/p>\r\n<p>但是人工智能在无人驾驶、个人智能助理、家庭机器人、智能专家系统未来都将会成熟起来，前景广阔。<\/p>\r\n<p>人类总是<stro**

# 到这里,后面的内容就没有了,请问是哪里出了问题,多谢.
我用的volley和httpUrlconnecttion都试过,都是这样.

**Comment by izzyleung** [comment]
抱歉，您对问题的描述过于模糊。
从提供的信息中，我无法了解您所使用的网络环境，以及如何重现问题。

不过有以下几个检查点您可以参考：
- 尝试在切换网络环境（从 Wi-Fi 切换至 数据流量，或者尝试不同 ISP 提供的网路陪）之后，重新获取数据
- 尝试切换设备，或者使用 Genymotion 之类的虚拟设备。
- 尝试不同版本的系统，最好确保系统未作修改。
- 清除 App 的本地数据，问题有可能是由 HTTP Library 的缓存所引起。

希望可以解决您的问题。

**Comment by jesse920524** [comment]
@izzyleung 
0.谢谢你的回复,在我没从事android开发前,就一直使用您写的知乎日报净化,频率是每天.真心的喜欢.
1.我尝试切换了网络,从wifi至联通4g,会出现同样的问题,所以排除网络原因.
2.我调试机型为google nexus5 6.0.1原生系统.
3.最重要的一点,仅仅是在log输出中出现了显示不全的问题,实际上webview显示是完全没有问题的!

**Comment by izzyleung** [comment]
呼，那么就没有问题了。

如果在 WebView 中内容可以得到完全的显示，则说明数据已经获取完全。
Android 系统中，LogCat 为了节省储存空间，限制了一条消息的长度。
具体情况可以参考 StackOverflow 中的这个回答：http://stackoverflow.com/a/8899735
