### ISSUE TITLE
文章短评论一次只能获取二十条，如何获取更多？

### ISSUE THREAD

**Issue by Cuixote** [izzyleung/ZhihuDailyPurify#23]
例：
`http://news-at.zhihu.com/api/4/story/4232852/short-comments`

原文评论有很多，但是只能获取20条，如何获取更多？

**Comment by YorekLiu** [comment]
后面接before/547091，547091是第20条短评的id
e.g.:
http://news-at.zhihu.com/api/4/story/4232852/short-comments/before/547091

另外，欢迎star我[模仿的知乎日报](https://github.com/YorekLiu/YLDailyZhihu)
