### ISSUE TITLE
api获取图片403，请问你是怎么解决的?

### ISSUE THREAD

**Issue by ishowman** [izzyleung/ZhihuDailyPurify#24]
数据能正确访问到，但图片链接加载时，显示403

**Comment by qiangzi7723** [comment]
这个问题我刚刚在做小程序的时候也遇到了，我估计应该是由于知乎对图片做了防盗链的操作，所以会返回403。而在浏览器能正常打开。如果需要破解，应该需要后端的配合，或者是在前端使用iframe，只是不知道这种方法能否奏效，愿共同探讨。

**Comment by qiangzi7723** [comment]
@ishowman 
解决办法已经找到了，纯前端的解决办法就是使用一个跳板链接到该图片地址。可以使用下面的这个

`http://read.html5.qq.com/image?src=forum&q=5&r=0&imgflag=7&imageUrl=`

假如需要破解防盗链的图片链接是这样的

`http://pic2.zhimg.com/552373ccd73d9d61a87c1917194bcf55.jpg`

那么使用了跳板之后的链接就是这样写

`http://read.html5.qq.com/image?src=forum&q=5&r=0&imgflag=7&imageUrl=http://pic2.zhimg.com/552373ccd73d9d61a87c1917194bcf55.jpg`

**Comment by ishowman** [comment]
@qiangzi7723 实在太谢谢了

**Comment by ishowman** [comment]
@qiangzi7723 还有个问题。用你的方法在本地所有图片都能正常显示，但在sae上，会被腾讯检测到并自动替换成警告图片。请问还有其它类似的方法可以解决吗？或者你告诉我这种方法的名字叫什么，我自己google。再次感谢！

**Comment by 349989153** [comment]
确实是日报的图片做了防盗链，原理是request的headers里有个Referer，这个的值必须是http://daily.zhihu.com/才行。

我解决的方法就是自己写个图片服务器，用服务器去发请求，改Referer。

`var express = require('express');
var request = require('request');
var app = express();

app.get('/images/*', function (req, res) {
  var imgUrl = req.protocol + '://' + req.url.substr(8);
  var options = {
    url: imgUrl,
    headers: {
      'Referer': 'http://daily.zhihu.com/',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
    }
  };

  req.pipe(request(options)).pipe(res);
});

var server = app.listen(9099, function () {
  console.log('img server is running on: ' + server.address().port);
})`

**Comment by Reckfu1** [comment]
@qiangzi7723 太感谢了。。自己研究了半天没弄出来。。

**Comment by Reckfu1** [comment]
@ishowman 跟你一样的情况 被检测到了 你解决了吗

**Comment by dclcats** [comment]
可以添加meta 标签 <meta name="referrer" content="never">
一个纯前端的解决方法
可以看看文章 http://www.cnblogs.com/dongcanliang/p/6655061.html

**Comment by lululuting** [comment]
感谢那个猫咪头像的仁兄
