### ISSUE TITLE
欢迎页面的地址失效了

### ISSUE THREAD

**Issue by guanzhirui** [izzyleung/ZhihuDailyPurify#25]
http://news-at.zhihu.com/api/4/start-image/720*1184
地址失效了

**Comment by a5216652166** [comment]
同求

**Comment by jk625x** [comment]
@guanzhirui @a5216652166 
新地址是这个
http://news-at.zhihu.com/api/7/prefetch-launch-images/1080*1920
`{"creatives": [{
    "url": "https://pic4.zhimg.com/v2-9f030a1d7bcfa8e8a7992d13d3592dbb.jpg",
    "text": "David Marcu",
    "start_time": 1488098865,
    "impression_tracks": ["https://sugar.zhihu.com/track?vs=1&ai=3297&ut=&cg=2&ts=1488098865.42&si=784a9fa178394160b3a9fa2fdf6935c5&lu=0&hn=ad-engine.ad-engine.b8859d8d&at=impression&pf=PC&az=11&sg=e0009ea2f3496b29016440593474ada1"],
    "landing_url": "https://www.zhihu.com/",
    "click_tracks": ["https://sugar.zhihu.com/track?vs=1&pf=PC&ai=3297&ut=&cg=2&ts=1488098865.42&si=784a9fa178394160b3a9fa2fdf6935c5&lu=0&lr=1&at=click&hn=ad-engine.ad-engine.b8859d8d&az=11&sg=e0009ea2f3496b29016440593474ada1"],
    "type": 0,
    "id": "3297"
}]}`

**Comment by a5216652166** [comment]
好人

**Comment by emmazh507** [comment]
为什么我这边打开是空的呢？
http://news-at.zhihu.com/api/7/prefetch-launch-images/1080*1920
{"creatives":[]}

online json tester提示  301 Moved Permanently ？

**Comment by izzyleung** [comment]
知乎已经将所有知乎日报 API 的流量迁徙到了 HTTPS 站。
