### ISSUE TITLE
大神过往消息那条api出了点问题啊

### ISSUE THREAD

**Issue by biaodigit** [izzyleung/ZhihuDailyPurify#30]
大神能帮忙查看查看么？已经无法加载以前的消息了

**Comment by LewisTian** [comment]
@biaodigit 我试了没有问题哇
![](https://user-images.githubusercontent.com/23132915/31850275-064172a6-b682-11e7-9ee4-729bbfccaa1c.png)

**Comment by biaodigit** [comment]
@LewisTian 但是很多仿知乎日报的加载更多那里都崩了，http:www.lwdvue.cn，这个我自己的，http://112.74.200.85:8888，http://zhihudaily-vue.yatessss.com/#!/，这些也崩了

**Comment by LewisTian** [comment]
@biaodigit 貌似是你加载过往信息before后面跟的不是日期 所以加载不出来啊
![daily.png](https://i.loli.net/2017/11/02/59fa6f564ebfe.png)
![daily2.png](https://i.loli.net/2017/11/02/59fa6f561e6ec.png)
