### ISSUE TITLE
声明是不是写错了？

### ISSUE THREAD

**Issue by YCF** [izzyleung/ZhihuDailyPurify#31]
以下所有 API 均由 知乎（Zhihu.Inc） 提供，本人（Xiao Liang）采取非正常手段获取。
应该是：
以下所有 API 均由 知乎（Zhihu.Inc） 提供，**非**本人（Xiao Liang）采取非正常手段获取。

**Comment by LewisTian** [comment]
这些API又没公开，当然是采取非正常的手段获取的啦（
