### ISSUE TITLE
关于主题日报过往新闻的API接口貌似没有给出

### ISSUE THREAD

**Issue by 1136535305** [izzyleung/ZhihuDailyPurify#32]
我用Fiddler找到的接口貌似是这个：

http://news-at.zhihu.com/api/4/theme/{themeId}/before/{newsId}

themeId:主题标志Id
newId  ：新闻Id，一般取上次获取的最后一条新闻ID

例：http://news-at.zhihu.com/api/4/theme/12/before/4731018

最后感谢一下作者的无私奉献

**Comment by izzyleung** [comment]
同样感谢你的无私贡献。

对应的内容已经添加在了文档的最新版本中。
