### ISSUE TITLE
关于构建

### ISSUE THREAD

**Issue by BurnieLau** [izzyleung/ZhihuDailyPurify#33]
你好 这个项目 怎么用 studio 直接打开 而不用 bazel

**Comment by izzyleung** [comment]
如果您只是想在 Android Studio 中打开并且编辑这个 Repository 中的代码，在 Android Studio 的选项中选择 Plugin 并安装名叫 Bazel 的插件，重新启动 Android Studio 后选择 `Import Bazel Project` 就好了。

但是如果您需要构建这个 App，目前唯一的途径只有 Bazel。
