### ISSUE TITLE
导入项目出错...

### ISSUE THREAD

**Issue by 1990jxy** [izzyleung/ZhihuDailyPurify#5]
在themes.xml中出现错误:
error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light.NoActionBar'.

**Comment by izzyleung** [comment]
这是由于 `AppCompat` 这个 Library 没有加入 IDE 的依赖列表做造成的。

在您没有提供关于您开发平台的更多信息之前，我可能没有办法给您提供更多的建议。

但是您可以尝试检查以下几个可能出错的地方：
- 请使用 `Android Studio` 而不是 `Android Development Tools`
- 请确保使用 `Android Studio` 的最新版本
- 请确保在导入项目的时候，按照以下流程完成。
  - 在 `Android Studio` 的主页面中，选择 `Import project (Eclipse ADT, Gradle, etc.)`
  - 在文件选择的对话框中，选择引入此项目根目录下的 `build.gradle` 文件以引入
  - `Android Studio` 会帮你完成剩余的配置，如果没有问题的话，项目便可以顺利地引入你的 IDE 中
- 请确保在第一次打开项目之时保持足够的耐心，`Android Studio` 会从 `Gradle` 的服务器下载编译所必须的依赖。国内的线路链接这个服务器的速度及其慢，可以考虑在全局翻墙之后再导入此项目。

如果还有什么问题，请在这个 Issue 下继续回复吧。

**Comment by 1990jxy** [comment]
感谢您的回复,我使用的工具是Eclipse,发现确实是因为AppCompat_v7 Library出错,此工程对于Target有要求么? AppCompat以删除添加数次无果.--||

**Comment by izzyleung** [comment]
这个项目的最低 SDK 要求是 15

或者如果您不介意麻烦的话，可以考虑编辑掉所有的和 AppCompat 有关的内容：比如把所有的 Activity 改成继承 FragmentActivity 并且编辑掉 res 中所有用到了 AppCompat 内容的 style。之后应该就没有问题了。

不过如果您只是需要参考逻辑部分代码的内容，并不用将项目编译运行的~
