### ISSUE TITLE
Passport使用新版知乎日报时遇见的问题

### ISSUE THREAD

**Issue by FreemanZ** [izzyleung/ZhihuDailyPurify#8]
1、Passport的键盘滑动得到了支持，但是只支持上下滑动而没有支持左右滑动；
2、在查看具体内容中，触屏上下滑动时左右抖动严重，经常出现不小心返回到首页。

**Comment by izzyleung** [comment]
请问您使用的是 Blackberry 的新手机 Passport 吗？

很抱歉我没有尝试过，身边也没有人使用 Blackberry 的手机，所以恐怕我很难帮助您解决这个问题。

我猜测您所遇到的问题是由于 Blackberry OS 对于 Android Apps 兼通不完善而造成的。

如果您有另外的 Android 设备，不妨在其上尝试运行这个 App，检测您所遇到的问题是否是因为 Blackberry OS 而造成的。
