### ISSUE TITLE
请问如何实现知乎日报的登陆账号？

### ISSUE THREAD

**Issue by CodingNinjaOctocat** [izzyleung/ZhihuDailyPurify#9]
知乎日报支持 “新浪微博”、“腾讯微博” 账号绑定，如果我使用 “xx微博” API，那么和官方的效果是一样的吗？可以获取 “xx微博” 收藏的文章吗？

**Comment by izzyleung** [comment]
如果仅仅是使用知乎日报的 App Key 引导用户登录，您所能过获取到的，只有微博授权的 Access Token。

知乎日报会利用获取的 Access Token 在服务器中查询相关的记录，调取用户的收藏相关信息。

而这一部分我没有做过多的探索，因为这势必会涉及到用户的隐私数据。

如果您愿意探索这一部分相关的逻辑，请您大胆地去做吧！

不过还是请您多多注意知乎的用户协定。
